export const REGISTER_USERNAME_MIN_LENGTH = 1;
export const REGISTER_USERNAME_MAX_LENGTH = 60;

export const REGISTER_LOGIN_MIN_LENGTH = 2;
export const REGISTER_LOGIN_MAX_LENGTH = 60;

export const REGISTER_PASSWORD_MIN_LENGTH = 6;
export const REGISTER_PASSWORD_MAX_LENGTH = 60;
